version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:8.12.2
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elk-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      retries: 5
      start_period: 30s

  logstash:
    image: logstash:8.12.2
    container_name: logstash
    restart: always
    volumes:
      - ./logstash/pipeline:/Users/consultadd/Documents/Elasticsearch/logstash/pipeline
      - ./logstash/config/logstash.yml:/Users/consultadd/Documents/Elasticsearch/logstash/config/logstash.yml
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk-network

  kibana:
    image: kibana:8.12.2
    container_name: kibana
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - elk-network

networks:
  elk-network:
    driver: bridge

volumes:
  elasticsearch-data: {}
